fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"
  service:
    mailer: 'fos_user.mailer.noop'
  registration:
    confirmation:
      enabled: true
      from_email:
        address: my_username@gmail.com
        sender_name: Demo registration