vich_uploader:
    db_driver: orm

    mappings:
        vich_files_upload:
            uri_prefix: /uploads/items
            upload_destination: "%kernel.project_dir%/public/uploads/items"
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
