version: 2.1
jobs:
    build:
        docker:
            - image: circleci/php:7.2
        
        steps:
            - checkout # Pull the source code
            - run:
                  name: Install Dependencies
                  command: |
                      composer install
            - run:
                  name: Set up Environment Variables
                  command: |
                      echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db" > .env.test
            - run:
                  name: Run Tests
                  command: |
                      bin/phpunit
    
    deploy:
        machine:
            enabled: true
        
        steps:
            - checkout # Pull the source code
            - run:
                  name: Install Dependencies
                  command: |
                      composer install --no-dev --optimize-autoloader
            - run:
                  name: Deploy Your Application
                  command: |
                      # You can add deployment commands here
                      # For example, deploying to a web server

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
