controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_user:
    # loads routes from the given routing file stored in some bundle
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'